version: '3.8'
services:
  dev-db:
    image: postgres:15
    port:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD : 123
      - POSTGRESH_DB : nest
    networks:
      - freecodecamp: